### ISSUE TITLE
500 when fetching certificate

### ISSUE THREAD

**Issue by csj** [noops-challenge/mazebot#4]
I completed the race, and got a URL for fetching my certificate! Following that URL produces:

Response code 500
{
    "message": "error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length"
}

**Comment by csj** [comment]
Hint: I was getting the same response before I started including a Content-Type:application/json header in my POSTs.

**Comment by davidmfoley** [comment]
Thanks for the report!
